name: Build and Release Debian Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version (e.g. v1.0.0)"
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        env:
          CI: true

      - name: Build the project
        run: bun build src/index.ts --outfile dist/index.js --target bun --format esm --minify

      - name: Run build-deb.sh script
        run: ./build-deb.sh
        shell: bash

      - name: Upload Debian package as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: discord-bot_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
