name: Build and Release Debian Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version (e.g. v1.0.0)"
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Authenticate npm for GitHub Packages
        run: npm config set //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Corepack and activate version from package.json
        run: |
          corepack enable
          corepack install

      - name: Install dependencies
        run: pnpm install --prod
        env:
          CI: true

      - name: Build the project
        run: pnpm run build

      - name: Run build-deb.sh script
        run: pnpm run build-deb

      - name: Upload Debian package as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: discord-bot_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
